package pantallas.juegos;

import java.awt.Color;
import java.awt.Font;
import java.util.concurrent.CompletableFuture;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import logicajuegos.PPT.JugadaPPT;
import pantallas.AppTheme;

/**
 *
 * @author LENOVO
 */
public class PPT extends javax.swing.JFrame {

    private final ImageIcon PIEDRA_ICO = new ImageIcon("src\\imagenes\\PiedraPPT.png");
    private final ImageIcon PAPEL_ICO = new ImageIcon("src\\imagenes\\PapelPPT.png");
    private final ImageIcon TIJERA_ICO = new ImageIcon("src\\imagenes\\TijeraPPT.png");
    
    public static final Color VERDE = new Color(0, 170, 95);
    public static final Color ROJO = new Color(120, 35, 55);
    public static final Color GRIS = new Color(55, 60, 63);
    
    private final JugadorPPTUI J = new JugadorPPTUI("Persona");
    private PartidaPPTUI P = PartidaPPTUI.crearPartida(J, 3, this);
    
    private Timer cuentaAtras;
    private CompletableFuture<JugadaPPT> jugadaPedida;
    
    /**
     * Creates new form PPT
     */
    public PPT() {
        initComponents();
        aplicarEstiloVisual();
    }

    private void aplicarEstiloVisual() {
        Color fondo = AppTheme.getFondoActivo();

        Panel_PPT.setBackground(fondo);
        iconoPerfil.setIcon(AppTheme.getIconoPerfilActivo());
        gon.setIcon(AppTheme.getPersonajePptActivo());

        marc_bot.setForeground(new Color(255, 0, 75));
        marc_bot.setFont(new Font("Dialog", Font.BOLD, 76));

        JLabel[] nombres = {nombre_bot, nombre_de_usuario};
        for (JLabel nombre : nombres) {
            nombre.setForeground(Color.WHITE);
            nombre.setFont(new Font("Dialog", Font.BOLD, 26));
        }

        JLabel[] etiquetas = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel8, jLabel9};
        for (JLabel etiqueta : etiquetas) {
            etiqueta.setForeground(Color.WHITE);
            etiqueta.setFont(new Font("Dialog", Font.BOLD, 20));
        }

        r1.setBackground(new Color(0, 170, 95));
        r2.setBackground(new Color(120, 35, 55));
        r3.setBackground(new Color(55, 60, 63));
        for (JLabel ronda : new JLabel[]{r1, r2, r3}) {
            ronda.setForeground(Color.WHITE);
            ronda.setBorder(BorderFactory.createLineBorder(new Color(6, 6, 6), 2));
        }

        gon.setBounds(1540, 300, 360, 500);
        iconoBot.setBounds(530, 870, 80, 80);
        iconoPerfil.setBounds(1310, 860, 90, 80);
        nombre_bot.setBounds(330, 950, 500, 60);
        nombre_de_usuario.setBounds(1130, 950, 440, 60);
        marc_bot.setBounds(750, 675, 460, 105);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Panel_PPT = new javax.swing.JPanel();
        BotonPiedra = new javax.swing.JButton();
        BotonPapel = new javax.swing.JButton();
        BotonTijera = new javax.swing.JButton();
        iconoPerfil = new javax.swing.JLabel();
        nombre_de_usuario = new javax.swing.JLabel();
        nombre_bot = new javax.swing.JLabel();
        marc_bot = new javax.swing.JLabel();
        iconoBot = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        piedraBot = new javax.swing.JLabel();
        papelBot = new javax.swing.JLabel();
        tijeraBot = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resultadoBot = new javax.swing.JLabel();
        papel = new javax.swing.JLabel();
        tijera = new javax.swing.JLabel();
        piedra = new javax.swing.JLabel();
        resultadoUser = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        marc_jug = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        gon = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_PPT.setBackground(new java.awt.Color(25, 25, 25));
        Panel_PPT.setMaximumSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setMinimumSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setPreferredSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonPiedra.setBorderPainted(false);
        BotonPiedra.setContentAreaFilled(false);
        BotonPiedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piedraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piedraMouseExited(evt);
            }
        });
        BotonPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPiedraActionPerformed(evt);
            }
        });
        Panel_PPT.add(BotonPiedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 490, 350, 140));

        BotonPapel.setBorderPainted(false);
        BotonPapel.setContentAreaFilled(false);
        BotonPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                papelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                papelMouseExited(evt);
            }
        });
        Panel_PPT.add(BotonPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 650, 350, 140));

        BotonTijera.setBorderPainted(false);
        BotonTijera.setContentAreaFilled(false);
        BotonTijera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tijeraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tijeraMouseExited(evt);
            }
        });
        Panel_PPT.add(BotonTijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 820, 350, 140));

        iconoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsUsuarioPerfil.png"))); // NOI18N
        Panel_PPT.add(iconoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 230, 120, 110));

        nombre_de_usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombre_de_usuario.setForeground(new java.awt.Color(255, 255, 255));
        nombre_de_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_de_usuario.setText("{nombre_de_usuario}");
        Panel_PPT.add(nombre_de_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 330, 230, 70));

        nombre_bot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombre_bot.setForeground(new java.awt.Color(255, 255, 255));
        nombre_bot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_bot.setText("{nombre_bot}");
        Panel_PPT.add(nombre_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 480, -1));

        marc_bot.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        marc_bot.setForeground(new java.awt.Color(0, 204, 204));
        marc_bot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marc_bot.setText("{marc_bot}");
        Panel_PPT.add(marc_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 940, 230, 90));

        iconoBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsBot.png"))); // NOI18N
        Panel_PPT.add(iconoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAPEL");
        Panel_PPT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, 120, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PIEDRA");
        Panel_PPT.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 120, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIJERA");
        Panel_PPT.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 870, 90, 30));

        piedraBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piedraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PiedraPPT.png"))); // NOI18N
        piedraBot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_PPT.add(piedraBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 200, 170));

        papelBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papelBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PapelPPT.jpg"))); // NOI18N
        Panel_PPT.add(papelBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        tijeraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TijeraPPT.png"))); // NOI18N
        Panel_PPT.add(tijeraBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 810, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAPEL");
        Panel_PPT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 710, 100, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PIEDRA");
        Panel_PPT.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 550, 100, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TIJERA");
        Panel_PPT.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 860, 80, 30));

        resultadoBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PiedraPPT.png"))); // NOI18N
        Panel_PPT.add(resultadoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 200, 170));

        papel.setBackground(new java.awt.Color(255, 255, 255));
        papel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PapelPPT.jpg"))); // NOI18N
        papel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_PPT.add(papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 640, -1, -1));

        tijera.setBackground(new java.awt.Color(255, 255, 255));
        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TijeraPPT.png"))); // NOI18N
        tijera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_PPT.add(tijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 800, -1, -1));

        piedra.setBackground(new java.awt.Color(255, 255, 255));
        piedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PiedraPPT.png"))); // NOI18N
        piedra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_PPT.add(piedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 470, 200, 170));

        resultadoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PiedraPPT.png"))); // NOI18N
        Panel_PPT.add(resultadoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 210, 170));

        r1.setBackground(new java.awt.Color(0, 255, 0));
        r1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r1.setOpaque(true);
        Panel_PPT.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 190, 60));

        r2.setBackground(new java.awt.Color(255, 0, 51));
        r2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r2.setOpaque(true);
        Panel_PPT.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 190, 60));

        r3.setBackground(new java.awt.Color(153, 153, 153));
        r3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r3.setOpaque(true);
        Panel_PPT.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 190, 60));

        marc_jug.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        marc_jug.setForeground(new java.awt.Color(102, 204, 0));
        marc_jug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marc_jug.setText("{marc_jug}");
        Panel_PPT.add(marc_jug, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 940, 230, 90));

        contador.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 0, 51));
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("{contador}");
        Panel_PPT.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 940, 230, 90));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPPT.png"))); // NOI18N
        Panel_PPT.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 4, 2010, 1160));

        gon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GonPPT.png"))); // NOI18N
        Panel_PPT.add(gon, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 960, 1120));

        getContentPane().add(Panel_PPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2260, 1250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseEntered
        piedra.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        piedra.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_piedraMouseEntered

    private void piedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseExited
        piedra.setBorder(null);
    }//GEN-LAST:event_piedraMouseExited

    private void papelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseEntered
        papel.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        papel.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_papelMouseEntered

    private void papelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseExited
        papel.setBorder(null);
    }//GEN-LAST:event_papelMouseExited

    private void tijeraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseEntered
        tijera.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        tijera.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_tijeraMouseEntered

    private void tijeraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tijeraMouseExited

    private void BotonPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPiedraActionPerformed
        hacerJugada(JugadaPPT.PIEDRA);
    }//GEN-LAST:event_BotonPiedraActionPerformed

    private void activarBotones(boolean activar) {
        BotonPiedra.setEnabled(activar);
        BotonPapel.setEnabled(activar);
        BotonTijera.setEnabled(activar);
    }
    
    protected void pedirJugada(CompletableFuture<JugadaPPT> jugadaPedida) {
        this.jugadaPedida = jugadaPedida;
        activarBotones(true);
        int[] segundos = {10}; // array para poder usarlo dentro del lambda

        cuentaAtras = new Timer(1000, e -> {
            segundos[0]--;
            contador.setText(String.valueOf(segundos[0])+"s");

            if (segundos[0] == 0) {
                ((Timer) e.getSource()).stop();
            }
        });

        cuentaAtras.start();
    }
    
    protected void pararCuentaAtras(){
        if(cuentaAtras.isRunning()){
            cuentaAtras.stop();
        }
        if(cuentaAtras != null){
            cuentaAtras = null;
        }
        contador.setText("-");
    }
    
    private void hacerJugada(int gesto) {
        try{
            J.hacerJugada(gesto, P, jugadaPedida);
            this.jugadaPedida = null;
            activarBotones(false);
        } catch(IllegalArgumentException IAEx) {
            //NO HACEMOS NA
        }
    }
    
    protected void mostrarJugadaPersona(int gesto){
        resultadoUser.setIcon(getIconoGesto(gesto));
    }
    
    protected void mostrarJugadaBot(int gesto){
        resultadoBot.setIcon(getIconoGesto(gesto));
    }
    
    private ImageIcon getIconoGesto(int gesto){
        ImageIcon ico = PIEDRA_ICO;
        switch(gesto){
            case JugadaPPT.PIEDRA -> ico = PIEDRA_ICO;
            case JugadaPPT.PAPEL -> ico = PAPEL_ICO;
            case JugadaPPT.TIJERA -> ico = TIJERA_ICO;
            default -> throw new IllegalArgumentException("Gesto no valido.");
        }
        return ico;
    }
    
    protected void resultadoRondaEMPATE() {
        switch(P.getTurno()){
            case 1 -> r1.setBackground(GRIS);
            case 2 -> r2.setBackground(GRIS);
            case 3 -> r3.setBackground(GRIS);
        }
    }
    
    protected void resultadoRondaGANA_J1() {
        Color c = P.getJugador1().equals(J)? VERDE : ROJO;
        switch(P.getTurno()){
            case 1 -> r1.setBackground(c);
            case 2 -> r2.setBackground(c);
            case 3 -> r3.setBackground(c);
        }
    }
    
    protected void resultadoRondaGANA_J2() {
        Color c = P.getJugador2().equals(J)? VERDE : ROJO;
        switch(P.getTurno()){
            case 1 -> r1.setBackground(c);
            case 2 -> r2.setBackground(c);
            case 3 -> r3.setBackground(c);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPapel;
    private javax.swing.JButton BotonPiedra;
    private javax.swing.JButton BotonTijera;
    private javax.swing.JPanel Panel_PPT;
    private javax.swing.JLabel contador;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel gon;
    private javax.swing.JLabel iconoBot;
    private javax.swing.JLabel iconoPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel marc_bot;
    private javax.swing.JLabel marc_jug;
    private javax.swing.JLabel nombre_bot;
    private javax.swing.JLabel nombre_de_usuario;
    private javax.swing.JLabel papel;
    private javax.swing.JLabel papelBot;
    private javax.swing.JLabel piedra;
    private javax.swing.JLabel piedraBot;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel resultadoBot;
    private javax.swing.JLabel resultadoUser;
    private javax.swing.JLabel tijera;
    private javax.swing.JLabel tijeraBot;
    // End of variables declaration//GEN-END:variables
}
