/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.juegos;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author LENOVO
 */
public class PPTLS extends javax.swing.JFrame {

    /**
     * Creates new form PPT
     */
    public PPTLS() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Panel_PPT = new javax.swing.JPanel();
        iconoPerfil = new javax.swing.JLabel();
        nombre_de_usuario = new javax.swing.JLabel();
        nombre_bot = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        Vs = new javax.swing.JLabel();
        iconoBot = new javax.swing.JLabel();
        bannerGris = new JLabelGradient();
        separadorNegro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        piedraBot = new javax.swing.JLabel();
        papelBot = new javax.swing.JLabel();
        tijeraBot = new javax.swing.JLabel();
        resultadoBot = new javax.swing.JLabel();
        resultadoUser = new javax.swing.JLabel();
        panelRondas = new javax.swing.JPanel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lagartoBot = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spockBot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        piedra = new javax.swing.JLabel();
        papel = new javax.swing.JLabel();
        tijera = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lagarto = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        spock = new javax.swing.JLabel();
        master_hand = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_PPT.setBackground(new java.awt.Color(255, 255, 255));
        Panel_PPT.setMaximumSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setMinimumSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setPreferredSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsUsuarioPerfil.png"))); // NOI18N
        Panel_PPT.add(iconoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 90, 80));

        nombre_de_usuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombre_de_usuario.setForeground(new java.awt.Color(0, 0, 0));
        nombre_de_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_de_usuario.setText("{nombre_de_usuario}");
        Panel_PPT.add(nombre_de_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, 290, 40));

        nombre_bot.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombre_bot.setForeground(new java.awt.Color(0, 0, 0));
        nombre_bot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_bot.setText("{nombre_bot}");
        Panel_PPT.add(nombre_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 280, 30));

        contador.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 0, 51));
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("{contador}");
        Panel_PPT.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 840, 460, 90));

        Vs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Street_FighterVS.png"))); // NOI18N
        Panel_PPT.add(Vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        iconoBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsBot.png"))); // NOI18N
        Panel_PPT.add(iconoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 80, -1));

        bannerGris.setOpaque(true);
        Panel_PPT.add(bannerGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 820, 210));

        separadorNegro.setBackground(new java.awt.Color(0, 0, 0));
        separadorNegro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        separadorNegro.setOpaque(true);
        Panel_PPT.add(separadorNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -30, 840, 260));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAPEL");
        Panel_PPT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 300, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PIEDRA");
        Panel_PPT.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 280, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIJERA");
        Panel_PPT.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 280, 30));

        piedraBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piedraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        piedraBot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_PPT.add(piedraBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 200, 170));

        papelBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papelBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel.png"))); // NOI18N
        Panel_PPT.add(papelBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        tijeraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera.png"))); // NOI18N
        Panel_PPT.add(tijeraBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        resultadoBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        Panel_PPT.add(resultadoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 200, 170));

        resultadoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        Panel_PPT.add(resultadoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 520, 200, 170));

        panelRondas.setLayout(new java.awt.GridLayout(1, 3));

        r1.setBackground(new java.awt.Color(0, 255, 0));
        r1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(0, 0, 0));
        r1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r1.setText("RONDA 1");
        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r1.setOpaque(true);
        panelRondas.add(r1);

        r2.setBackground(new java.awt.Color(255, 0, 51));
        r2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r2.setForeground(new java.awt.Color(0, 0, 0));
        r2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r2.setText("RONDA 2");
        r2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r2.setOpaque(true);
        panelRondas.add(r2);

        r3.setBackground(new java.awt.Color(153, 153, 153));
        r3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r3.setForeground(new java.awt.Color(0, 0, 0));
        r3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r3.setText("RONDA 3");
        r3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r3.setOpaque(true);
        panelRondas.add(r3);

        Panel_PPT.add(panelRondas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 990, 380, 100));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setOpaque(true);
        Panel_PPT.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 980, 400, 110));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RONDAS");
        Panel_PPT.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 940, 200, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LAGARTO");
        Panel_PPT.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 820, 280, 30));

        lagartoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lagarto.png"))); // NOI18N
        Panel_PPT.add(lagartoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SPOCK");
        Panel_PPT.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 820, 280, 30));

        spockBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spock.png"))); // NOI18N
        Panel_PPT.add(spockBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 660, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PAPEL");
        Panel_PPT.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 590, 220, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PIEDRA");
        Panel_PPT.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 440, 280, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("TIJERA");
        Panel_PPT.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 580, 280, 30));

        piedra.setBackground(new java.awt.Color(255, 255, 255));
        piedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        piedra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        piedra.setOpaque(true);
        piedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piedraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piedraMouseExited(evt);
            }
        });
        Panel_PPT.add(piedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 270, 200, 170));

        papel.setBackground(new java.awt.Color(255, 255, 255));
        papel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel.png"))); // NOI18N
        papel.setOpaque(true);
        papel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                papelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                papelMouseExited(evt);
            }
        });
        Panel_PPT.add(papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 430, -1, -1));

        tijera.setBackground(new java.awt.Color(255, 255, 255));
        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tijera.png"))); // NOI18N
        tijera.setOpaque(true);
        tijera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tijeraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tijeraMouseExited(evt);
            }
        });
        Panel_PPT.add(tijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LAGARTO");
        Panel_PPT.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 820, 280, 30));

        lagarto.setBackground(new java.awt.Color(255, 255, 255));
        lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lagarto.png"))); // NOI18N
        lagarto.setOpaque(true);
        lagarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lagartoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lagartoMouseExited(evt);
            }
        });
        Panel_PPT.add(lagarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 660, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SPOCK");
        Panel_PPT.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 820, 280, 30));

        spock.setBackground(new java.awt.Color(255, 255, 255));
        spock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spock.png"))); // NOI18N
        spock.setOpaque(true);
        spock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spockMouseExited(evt);
            }
        });
        Panel_PPT.add(spock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 660, -1, -1));

        master_hand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        master_hand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Master_Hand.png"))); // NOI18N
        Panel_PPT.add(master_hand, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -70, 940, 770));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("=");
        Panel_PPT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("=");
        Panel_PPT.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 540, -1, -1));

        getContentPane().add(Panel_PPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2010, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tijeraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseEntered
        tijera.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        tijera.setBackground(Color.YELLOW);
    }//GEN-LAST:event_tijeraMouseEntered

    private void tijeraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseExited
        tijera.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        tijera.setBackground(Color.WHITE);
    }//GEN-LAST:event_tijeraMouseExited

    private void piedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseEntered
        piedra.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        piedra.setBackground(Color.YELLOW);
    }//GEN-LAST:event_piedraMouseEntered

    private void piedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseExited
        piedra.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        piedra.setBackground(Color.WHITE);
    }//GEN-LAST:event_piedraMouseExited

    private void papelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseEntered
        papel.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        papel.setBackground(Color.YELLOW);
    }//GEN-LAST:event_papelMouseEntered

    private void papelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseExited
        papel.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        papel.setBackground(Color.WHITE);
    }//GEN-LAST:event_papelMouseExited

    private void lagartoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseEntered
        lagarto.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        lagarto.setBackground(Color.YELLOW);
    }//GEN-LAST:event_lagartoMouseEntered

    private void lagartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseExited
        lagarto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        lagarto.setBackground(Color.WHITE);
    }//GEN-LAST:event_lagartoMouseExited

    private void spockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseEntered
        spock.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        spock.setBackground(Color.YELLOW);
    }//GEN-LAST:event_spockMouseEntered

    private void spockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseExited
        spock.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        spock.setBackground(Color.WHITE);
    }//GEN-LAST:event_spockMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPTLS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_PPT;
    private javax.swing.JLabel Vs;
    private javax.swing.JLabel bannerGris;
    private javax.swing.JLabel contador;
    private javax.swing.JLabel iconoBot;
    private javax.swing.JLabel iconoPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lagarto;
    private javax.swing.JLabel lagartoBot;
    private javax.swing.JLabel master_hand;
    private javax.swing.JLabel nombre_bot;
    private javax.swing.JLabel nombre_de_usuario;
    private javax.swing.JPanel panelRondas;
    private javax.swing.JLabel papel;
    private javax.swing.JLabel papelBot;
    private javax.swing.JLabel piedra;
    private javax.swing.JLabel piedraBot;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel resultadoBot;
    private javax.swing.JLabel resultadoUser;
    private javax.swing.JLabel separadorNegro;
    private javax.swing.JLabel spock;
    private javax.swing.JLabel spockBot;
    private javax.swing.JLabel tijera;
    private javax.swing.JLabel tijeraBot;
    // End of variables declaration//GEN-END:variables
}
