package pantallas.juegos;

import CRUD_bbdd.bbdd_operaciones;
import pantallas.Difuminar;
import java.awt.Color;
import static java.awt.Color.cyan;
import java.awt.Font;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;
import logicajuegos.PPT.JugadaPPT;
import logicajuegos.PPT.JugadaPPTLS;
import logicajuegos.PPT.JugadorPPTLS;
import pantallas.AppTheme;
import pantallas.Main_Juego;
import static pantallas.juegos.PPT.GRIS;
import static pantallas.juegos.PPT.ROJO;
import static pantallas.juegos.PPT.VERDE;

/**
 *
 * @author LENOVO
 */
public class PPTLS extends javax.swing.JFrame {

    private final ImageIcon PIEDRA_ICO = new ImageIcon("src\\imagenes\\roca.png");
    private final ImageIcon PAPEL_ICO = new ImageIcon("src\\imagenes\\papel.png");
    private final ImageIcon TIJERA_ICO = new ImageIcon("src\\imagenes\\tijera.png");
    private final ImageIcon LAGARTO_ICO = new ImageIcon("src\\imagenes\\Lagarto.png");
    private final ImageIcon SPOCK_ICO = new ImageIcon("src\\imagenes\\spock.png");

    private final JugadorPPTLSUI J = new JugadorPPTLSUI("Persona");
    private PartidaPPTLSUI P = PartidaPPTLSUI.crearPartida(J, 3, this);

    private Timer cuentaAtras;
    private CompletableFuture<JugadaPPT> jugadaPedida;
    private int vecesPiedra;
    private int vecesPapel;
    private int vecesTijera;
    private int vecesLagarto;
    private int vecesSpock;
    private boolean resultadoRegistrado;

    /**
     * Creates new form PPTLS
     */
    public PPTLS() {
        initComponents();
        aplicarEstiloVisual();
        activarBotones(false);
        resetRondas();
        setNombresJugadores();

        //mostrarPuntos();
        contador.setText("-");
        textoInit.setText("Empezar Partida");
    }

    private void aplicarEstiloVisual() {
        Color fondo = AppTheme.getFondoActivo();
        Color neon = new Color(0, 255, 160);
        Color cyan = new Color(0, 210, 255);

        Panel_PPT.setBackground(fondo);
        iconoPerfil.setIcon(AppTheme.getIconoPerfilActivo());
        master_hand.setIcon(AppTheme.getPersonajePptlsActivo());

        contador.setForeground(new Color(255, 0, 75));
        contador.setFont(new Font("Dialog", Font.BOLD, 76));

        JLabel[] nombres = {nombre_bot, nombre_de_usuario};
        for (JLabel nombre : nombres) {
            nombre.setForeground(Color.WHITE);
            nombre.setFont(new Font("Dialog", Font.BOLD, 24));
        }

        JLabel[] etiquetas = {
            jLabel1, jLabel3, jLabel4, jLabelLagart, jLabel11,
            jLabel12, jLabel13, jLabel67, jLabel15, jLabel16
        };
        for (JLabel etiqueta : etiquetas) {
            etiqueta.setForeground(Color.WHITE);
            etiqueta.setFont(new Font("Dialog", Font.BOLD, 18));

        }
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//
//        r1.setBackground(new Color(0, 170, 95));
//        r2.setBackground(new Color(120, 35, 55));
//        r3.setBackground(new Color(55, 60, 63));
//        for (JLabel ronda : new JLabel[]{r1, r2, r3}) {
//            ronda.setForeground(Color.WHITE);
//            ronda.setBorder(BorderFactory.createLineBorder(new Color(6, 6, 6), 2));
//        }

        master_hand.setBounds(-150, -40, 900, 720);
        iconoBot.setBounds(680, 60, 80, 80);
        iconoPerfil.setBounds(1210, 50, 90, 80);
        nombre_bot.setBounds(560, 150, 320, 40);
        nombre_de_usuario.setBounds(1090, 150, 330, 40);
        contador.setBounds(750, 835, 460, 95);

        Resultado.setBackground(new Color(12, 18, 20));
        Resultado.setBorder(javax.swing.BorderFactory.createLineBorder(neon, 3));
        RESULTADO.setForeground(Color.WHITE);
        RESULTADO.setFont(new Font("Dialog", Font.BOLD, 58));
        Panel_Volver.setBackground(new Color(0, 110, 80));
        Panel_Salir.setBackground(new Color(16, 28, 34));
        jLabel10.setForeground(Color.WHITE);
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(neon, 2));
        jLabel14.setText("Salir al Menu");
        jLabel14.setForeground(Color.WHITE);
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(cyan, 2));
        for (JLabel borde : new JLabel[]{jLabel15, jLabel16, jLabel10, jLabel14}) {
            borde.setBackground(new Color(0, 0, 0));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        Resultado = new javax.swing.JPanel();
        RESULTADO = new javax.swing.JLabel();
        Panel_Volver = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Panel_Salir = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Panel_PPT = new javax.swing.JPanel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        iconoPerfil = new javax.swing.JLabel();
        nombre_de_usuario = new javax.swing.JLabel();
        nombre_bot = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        iconoBot = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        piedraBot = new javax.swing.JLabel();
        papelBot = new javax.swing.JLabel();
        tijeraBot = new javax.swing.JLabel();
        resultadoBot = new javax.swing.JLabel();
        resultadoUser = new javax.swing.JLabel();
        jLabelLagart = new javax.swing.JLabel();
        lagartoBot = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spockBot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        piedra = new javax.swing.JLabel();
        papel = new javax.swing.JLabel();
        tijera = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lagarto = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        spock = new javax.swing.JLabel();
        continuarTurno = new javax.swing.JPanel();
        textoInit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fondoPPTLS = new javax.swing.JLabel();
        master_hand = new Difuminar();

        jLabel7.setText("jLabel7");

        jDialog1.setUndecorated(true);
        jDialog1.setResizable(false);

        Resultado.setBackground(new java.awt.Color(255, 255, 255));
        Resultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RESULTADO.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        RESULTADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RESULTADO.setText("{mostrar_resultado}");
        Resultado.add(RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 620, 100));

        Panel_Volver.setBackground(new java.awt.Color(255, 255, 102));
        Panel_Volver.setLayout(new java.awt.CardLayout());

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Volver a Jugar");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        Panel_Volver.add(jLabel10, "card2");

        Resultado.add(Panel_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 260, 100));

        Panel_Salir.setBackground(new java.awt.Color(0, 204, 255));
        Panel_Salir.setLayout(new java.awt.CardLayout());

        jLabel14.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Salir al Menú");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        Panel_Salir.add(jLabel14, "card2");

        Resultado.add(Panel_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 260, 100));

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setToolTipText("");
        jLabel19.setOpaque(true);
        Resultado.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 20, 550));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setToolTipText("");
        jLabel20.setOpaque(true);
        Resultado.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 20));

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setToolTipText("");
        jLabel21.setOpaque(true);
        Resultado.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 850, 20));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setToolTipText("");
        jLabel22.setOpaque(true);
        Resultado.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 20, 550));

        jDialog1.getContentPane().add(Resultado, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_PPT.setBackground(new java.awt.Color(255, 255, 255));
        Panel_PPT.setMaximumSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setMinimumSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setPreferredSize(new java.awt.Dimension(1920, 1090));
        Panel_PPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r1.setBackground(new java.awt.Color(0, 255, 0));
        r1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r1.setOpaque(true);
        Panel_PPT.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 960, 170, 50));

        r2.setBackground(new java.awt.Color(255, 0, 51));
        r2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r2.setOpaque(true);
        Panel_PPT.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 960, 160, 50));

        r3.setBackground(new java.awt.Color(153, 153, 153));
        r3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        r3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r3.setOpaque(true);
        Panel_PPT.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 960, 170, 50));

        iconoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsUsuarioPerfil.png"))); // NOI18N
        Panel_PPT.add(iconoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 90, 110, 100));

        nombre_de_usuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombre_de_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_de_usuario.setText("{nombre_de_usuario}");
        Panel_PPT.add(nombre_de_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 110, 330, 60));

        nombre_bot.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombre_bot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_bot.setText("{nombre_bot}");
        Panel_PPT.add(nombre_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 310, 60));

        contador.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 0, 51));
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("{contador}");
        Panel_PPT.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 810, 190, 90));

        iconoBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsBot.png"))); // NOI18N
        Panel_PPT.add(iconoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 80, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAPEL");
        Panel_PPT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 100, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PIEDRA");
        Panel_PPT.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIJERA");
        Panel_PPT.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 140, 30));

        piedraBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piedraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        piedraBot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_PPT.add(piedraBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 200, 170));

        papelBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papelBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel.png"))); // NOI18N
        Panel_PPT.add(papelBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 190, 150));

        tijeraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera.png"))); // NOI18N
        Panel_PPT.add(tijeraBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        resultadoBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        Panel_PPT.add(resultadoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 220, 170));

        resultadoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        Panel_PPT.add(resultadoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 200, 170));

        jLabelLagart.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelLagart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLagart.setText("LAGARTO");
        Panel_PPT.add(jLabelLagart, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 790, 140, 30));

        lagartoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lagarto.png"))); // NOI18N
        Panel_PPT.add(lagartoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SPOCK");
        Panel_PPT.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 800, 100, 30));

        spockBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spock.png"))); // NOI18N
        Panel_PPT.add(spockBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PAPEL");
        Panel_PPT.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 590, 120, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PIEDRA");
        Panel_PPT.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 370, 110, 30));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("TIJERA");
        Panel_PPT.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 590, 140, 30));

        piedra.setBackground(new java.awt.Color(255, 255, 255));
        piedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roca.png"))); // NOI18N
        piedra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        piedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piedraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piedraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piedraMouseExited(evt);
            }
        });
        Panel_PPT.add(piedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 220, 200, 150));

        papel.setBackground(new java.awt.Color(255, 255, 255));
        papel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel.png"))); // NOI18N
        papel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                papelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                papelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                papelMouseExited(evt);
            }
        });
        Panel_PPT.add(papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 430, 180, -1));

        tijera.setBackground(new java.awt.Color(255, 255, 255));
        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tijera.png"))); // NOI18N
        tijera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tijeraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tijeraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tijeraMouseExited(evt);
            }
        });
        Panel_PPT.add(tijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 430, -1, 160));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LAGARTO");
        Panel_PPT.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 810, 140, 30));

        lagarto.setBackground(new java.awt.Color(255, 255, 255));
        lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lagarto.png"))); // NOI18N
        lagarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lagartoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lagartoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lagartoMouseExited(evt);
            }
        });
        Panel_PPT.add(lagarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 660, 180, 150));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SPOCK");
        Panel_PPT.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 810, 130, 30));

        spock.setBackground(new java.awt.Color(255, 255, 255));
        spock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spock.png"))); // NOI18N
        spock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spockMouseExited(evt);
            }
        });
        Panel_PPT.add(spock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 650, -1, 150));

        continuarTurno.setBackground(new java.awt.Color(0, 102, 102));
        continuarTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarTurnoMouseClicked(evt);
            }
        });
        continuarTurno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoInit.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        textoInit.setForeground(new java.awt.Color(0, 204, 204));
        textoInit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInit.setText("EMPEZAR PARTIDA");
        textoInit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continuarTurno.add(textoInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 12, 250, 90));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setOpaque(true);
        continuarTurno.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 10));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setOpaque(true);
        continuarTurno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 10));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setOpaque(true);
        continuarTurno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 10, 110));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        continuarTurno.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 100));

        Panel_PPT.add(continuarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 630, 270, 110));

        fondoPPTLS.setBackground(new java.awt.Color(0, 0, 0));
        fondoPPTLS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoPPTLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPPTLS.png"))); // NOI18N
        Panel_PPT.add(fondoPPTLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 2010, 1090));

        master_hand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        master_hand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Master_Hand.png"))); // NOI18N
        Panel_PPT.add(master_hand, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 940, 1040));

        getContentPane().add(Panel_PPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2010, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tijeraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseEntered
        tijera.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        tijera.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_tijeraMouseEntered

    private void tijeraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseExited
        tijera.setBorder(null);
    }//GEN-LAST:event_tijeraMouseExited

    private void piedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseEntered
        piedra.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        piedra.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_piedraMouseEntered

    private void piedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseExited
        piedra.setBorder(null);
    }//GEN-LAST:event_piedraMouseExited

    private void papelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseEntered
        papel.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        papel.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_papelMouseEntered

    private void papelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseExited
        papel.setBorder(null);
    }//GEN-LAST:event_papelMouseExited

    private void lagartoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseEntered
        lagarto.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        lagarto.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_lagartoMouseEntered

    private void lagartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseExited
        lagarto.setBorder(null);
    }//GEN-LAST:event_lagartoMouseExited

    private void spockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseEntered
        spock.setBorder(BorderFactory.createLineBorder(new Color(0, 255, 160), 3));
        spock.setBackground(new Color(18, 45, 43));
    }//GEN-LAST:event_spockMouseEntered

    private void spockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseExited
        spock.setBorder(null);
    }//GEN-LAST:event_spockMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        P = PartidaPPTLSUI.crearPartida(J, 3, this);
        setNombresJugadores();
        textoInit.setText("Empezar Partida");
        continuarTurno.setVisible(true);
        continuarTurno.setEnabled(true);
        resetResultados();
        resetRondas();
//        mostrarPuntos();
        jDialog1.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        new Main_Juego().setVisible(true);
        this.dispose();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void piedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseClicked
        hacerJugada(JugadaPPTLS.PIEDRA);
    }//GEN-LAST:event_piedraMouseClicked

    private void papelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseClicked
        hacerJugada(JugadaPPTLS.PAPEL);
    }//GEN-LAST:event_papelMouseClicked

    private void tijeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseClicked
        hacerJugada(JugadaPPTLS.TIJERA);
    }//GEN-LAST:event_tijeraMouseClicked

    private void lagartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseClicked
        hacerJugada(JugadaPPTLS.LAGARTO);
    }//GEN-LAST:event_lagartoMouseClicked

    private void spockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseClicked
        hacerJugada(JugadaPPTLS.SPOCK);
    }//GEN-LAST:event_spockMouseClicked

    private void continuarTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarTurnoMouseClicked
        if (!P.isPartidaEnCurso() && P.devolverResultado().isEmpty()) {
            iniciarJuego();
            textoInit.setText("Siguiente Turno");
        } else {
            siguienteTurno();
        }
        continuarTurno.setEnabled(false);
        continuarTurno.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_continuarTurnoMouseClicked

    private void iniciarJuego() {
        new Thread(() -> {
            P.iniciarJuego();
        }).start();
    }

    private void siguienteTurno() {
        new Thread(() -> {
            P.siguienteTurno();
        }).start();
    }

    private void setNombresJugadores() {
        if (P.getJugador1() instanceof JugadorPPTLSUI) {
            nombre_de_usuario.setText(P.getJugador1().getNombre());
            nombre_bot.setText(P.getJugador2().getNombre());
        } else {
            nombre_de_usuario.setText(P.getJugador2().getNombre());
            nombre_bot.setText(P.getJugador1().getNombre());
        }
    }

    private void activarBotones(boolean activar) {
        piedra.setEnabled(activar);
        papel.setEnabled(activar);
        tijera.setEnabled(activar);
        lagarto.setEnabled(activar);
        spock.setEnabled(activar);
    }

    private void resetResultados() {
        resultadoUser.setBorder(null);
        resultadoUser.setIcon(null);
        resultadoBot.setBorder(null);
        resultadoBot.setIcon(null);
    }

    private void resetRondas() {
        r1.setBackground(null);
        r2.setBackground(null);
        r3.setBackground(null);
    }

    protected void pedirJugada(CompletableFuture<JugadaPPT> jugadaPedida) {
        resetResultados();
        pararCuentaAtras();
        this.jugadaPedida = jugadaPedida;
        activarBotones(true);

        int[] segundos = {10};
        cuentaAtras = new Timer(1000, e -> {
            segundos[0]--;
            contador.setText(segundos[0] + "s");
            if (segundos[0] == 0) {
                ((Timer) e.getSource()).stop();
            }
        });
        cuentaAtras.start();
    }

    protected void pararCuentaAtras() {
        if (cuentaAtras != null) {
            cuentaAtras.stop();
            cuentaAtras = null;
        }
        contador.setText("-");
    }

    private void hacerJugada(int gesto) {
        try {
            registrarGestoUsuario(gesto);
            J.hacerJugada(gesto, P, jugadaPedida);
            this.jugadaPedida = null;
            activarBotones(false);
            pararCuentaAtras();
        } catch (IllegalArgumentException IAEx) {
            throw new IllegalArgumentException("Jugada no valida.");
        }
    }

    protected void mostrarJugadaPersona(int gesto) {
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoUser.setIcon(getIconoGesto(gesto));
    }

    protected void mostrarJugadaBot(int gesto) {
        try {
            Thread.sleep(160);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoBot.setIcon(getIconoGesto(gesto));
    }

    private ImageIcon getIconoGesto(int gesto) {
        ImageIcon ico = PIEDRA_ICO;
        switch (gesto) {
            case JugadaPPTLS.PIEDRA ->
                ico = PIEDRA_ICO;
            case JugadaPPTLS.PAPEL ->
                ico = PAPEL_ICO;
            case JugadaPPTLS.TIJERA ->
                ico = TIJERA_ICO;
            case JugadaPPTLS.LAGARTO ->
                ico = LAGARTO_ICO;
            case JugadaPPTLS.SPOCK ->
                ico = SPOCK_ICO;
            default ->
                throw new IllegalArgumentException("Gesto no valido.");
        }
        return ico;
    }

    protected void mostrarPuntos() {
        int puntosUser = P.getJugador1().equals(J) ? P.getPuntosJ1() : P.getPuntosJ2();
        int puntosBot = P.getJugador2().equals(J) ? P.getPuntosJ1() : P.getPuntosJ2();
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        //marc_jug.setText(String.valueOf(puntosUser));
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        //marc_bot.setText(String.valueOf(puntosBot));
    }

    protected void resultadoRondaEMPATE() {
        switch (P.getTurno()) {
            case 1 ->
                r1.setBackground(GRIS);
            case 2 ->
                r2.setBackground(GRIS);
            case 3 ->
                r3.setBackground(GRIS);
            default ->
                throw new IllegalArgumentException("Turno no valido.");
        }
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoUser.setBorder(BorderFactory.createLineBorder(GRIS));
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoBot.setBorder(BorderFactory.createLineBorder(GRIS));
    }

    protected void resultadoRondaGANA_J1() {
        Color c = P.getJugador1().equals(J) ? VERDE : ROJO;
        switch (P.getTurno()) {
            case 1 ->
                r1.setBackground(c);
            case 2 ->
                r2.setBackground(c);
            case 3 ->
                r3.setBackground(c);
            default ->
                throw new IllegalArgumentException("Turno no valido.");
        }
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoUser.setBorder(BorderFactory.createLineBorder(c));
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoBot.setBorder(BorderFactory.createLineBorder(c.equals(VERDE) ? ROJO : VERDE));
    }

    protected void resultadoRondaGANA_J2() {
        Color c = P.getJugador2().equals(J) ? VERDE : ROJO;
        switch (P.getTurno()) {
            case 1 ->
                r1.setBackground(c);
            case 2 ->
                r2.setBackground(c);
            case 3 ->
                r3.setBackground(c);
            default ->
                throw new IllegalArgumentException("Turno no valido.");
        }
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoUser.setBorder(BorderFactory.createLineBorder(c));
        try {
            Thread.sleep(80);
        } catch (InterruptedException ex) {
            Logger.getLogger(PPTLS.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultadoBot.setBorder(BorderFactory.createLineBorder(c.equals(VERDE) ? ROJO : VERDE));
    }

    protected void mostrarResultado(int EMPATE) {
        registrarResultadoPPTLS(false);

        RESULTADO.setText("¡EMPATE!");
        Resultado.setBackground(new Color(45, 50, 55));

        mostrarDialogResultado();
    }

    protected void mostrarResultado(JugadorPPTLS ganador) {
        registrarResultadoPPTLS(ganador.equals(J));

        if (ganador.equals(J)) {

            RESULTADO.setText("¡HAS GANADO!");
            Resultado.setBackground(new Color(0, 90, 60));

        } else {

            RESULTADO.setText("Has perdido...");
            Resultado.setBackground(new Color(95, 20, 36));
        }

        mostrarDialogResultado();
    }

    private void mostrarDialogResultado() {
        jDialog1.setSize(850, 590);
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setModal(true);
        jDialog1.setVisible(true);
    }

    private void resetEstadisticasPartida() {
        vecesPiedra = 0;
        vecesPapel = 0;
        vecesTijera = 0;
        vecesLagarto = 0;
        vecesSpock = 0;
        resultadoRegistrado = false;
    }

    private void registrarGestoUsuario(int gesto) {
        switch (gesto) {
            case JugadaPPTLS.PIEDRA ->
                vecesPiedra++;

            case JugadaPPTLS.PAPEL ->
                vecesPapel++;

            case JugadaPPTLS.TIJERA ->
                vecesTijera++;

            case JugadaPPTLS.LAGARTO ->
                vecesLagarto++;

            case JugadaPPTLS.SPOCK ->
                vecesSpock++;

            default ->
                throw new IllegalArgumentException("Gesto no valido.");
        }
    }

    private void registrarResultadoPPTLS(boolean partidaGanada) {

        if (resultadoRegistrado) {
            return;
        }

        int puntosUsuario
                = (vecesPiedra
                + vecesPapel
                + vecesTijera
                + vecesLagarto
                + vecesSpock) * 2;

        if (partidaGanada) {
            puntosUsuario += 25;

        } else if (P.devolverGanador().isEmpty()) {
            puntosUsuario += 10;
        }

        bbdd_operaciones.registrarResultadoPPTLS(
                AppTheme.getNombreUsuarioActivo(),
                vecesPiedra,
                vecesPapel,
                vecesTijera,
                vecesLagarto,
                vecesSpock,
                partidaGanada,
                puntosUsuario
        );

        resultadoRegistrado = true;
    }

    public void mostrarBotonContinuar() {
        continuarTurno.setEnabled(true);
        continuarTurno.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPTLS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_PPT;
    private javax.swing.JPanel Panel_Salir;
    private javax.swing.JPanel Panel_Volver;
    private javax.swing.JLabel RESULTADO;
    private javax.swing.JPanel Resultado;
    private javax.swing.JLabel contador;
    private javax.swing.JPanel continuarTurno;
    private javax.swing.JLabel fondoPPTLS;
    private javax.swing.JLabel iconoBot;
    private javax.swing.JLabel iconoPerfil;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLagart;
    private javax.swing.JLabel lagarto;
    private javax.swing.JLabel lagartoBot;
    private javax.swing.JLabel master_hand;
    private javax.swing.JLabel nombre_bot;
    private javax.swing.JLabel nombre_de_usuario;
    private javax.swing.JLabel papel;
    private javax.swing.JLabel papelBot;
    private javax.swing.JLabel piedra;
    private javax.swing.JLabel piedraBot;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel resultadoBot;
    private javax.swing.JLabel resultadoUser;
    private javax.swing.JLabel spock;
    private javax.swing.JLabel spockBot;
    private javax.swing.JLabel textoInit;
    private javax.swing.JLabel tijera;
    private javax.swing.JLabel tijeraBot;
    // End of variables declaration//GEN-END:variables
}
