CREATE DATABASE DESAFIO_GRUPO6;

USE DESAFIO_GRUPO6;




CREATE TABLE TIENDA (
  ID_ARTICULO INT PRIMARY KEY NOT NULL UNIQUE,
  NOMBRE VARCHAR(20) NULL DEFAULT NULL,
  PRECIO INT NULL DEFAULT NULL,
  ID_TIENDA INT NOT NULL UNIQUE
);


CREATE TABLE USUARIO (
  ID_USUARIO INT PRIMARY KEY NOT NULL UNIQUE,
  NOMBRE_USUARIO VARCHAR(20) NOT NULL,
  CORREO VARCHAR(50) NOT NULL,
  CONTRASEÑA VARCHAR(45) NOT NULL
 );



CREATE TABLE JUGADOR (
  ID_JUGADOR INT PRIMARY KEY NOT NULL UNIQUE,
  `%VICTORIAS` INT NOT NULL,
  PUNTOS INT NOT NULL,
  ULTIMA_CONEXION DATETIME NOT NULL,
  ARTICULOS INT NOT NULL,
  ID_USUARIO INT NULL,
  FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);


CREATE TABLE ADMINISTRADOR (
  ID_ADMINISTRADOR INT PRIMARY KEY NOT NULL UNIQUE,
  ID_USUARIO INT NOT NULL,
  FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE PPTLS (
  ID_PPTLS INT PRIMARY KEY NOT NULL UNIQUE,
  PIEDRA INT NULL,
  PAPEL INT NULL,
  TIJERA INT NULL,
  LAGARTO INT NULL,
  SPOCK INT NULL
);

CREATE TABLE PPT (
  ID_PPT INT PRIMARY KEY NOT NULL UNIQUE,
  PIEDRA INT NULL,
  PAPEL INT NULL,
  TIJERA INT NULL
);


CREATE TABLE 3_EN_RAYA (
  ID_3_EN_RAYA INT PRIMARY KEY NOT NULL UNIQUE,
  `1` INT NULL,
  `2` INT NULL,
  `3` INT NULL,
  `4` INT NULL,
  `5` INT NULL,
  `6` INT NULL,
  `7` INT NULL,
  `8` INT NULL,
  `9` INT NULL
);  

CREATE TABLE PARTIDOS (
  ID_PARTIDA INT PRIMARY KEY NOT NULL,
  FECHA DATETIME NOT NULL,
  GANADOR INT NOT NULL,
  ID_PPTLS INT NOT NULL,
  FOREIGN KEY(ID_PPTLS) REFERENCES PPTLS(ID_PPTLS),
  ID_PPT INT NOT NULL,
  FOREIGN KEY(ID_PPT) REFERENCES PPT(ID_PPT),
  ID_3_EN_RAYA INT NOT NULL,
  FOREIGN KEY(ID_3_EN_RAYA) REFERENCES 3_EN_RAYA(ID_3_EN_RAYA)
  ON DELETE CASCADE
  ON UPDATE CASCADE
  );


CREATE TABLE Jugador_Partidos (
  ID_JUGADOR INT NOT NULL,
  ID_PARTIDA INT NOT NULL,
  PRIMARY KEY (ID_JUGADOR, ID_PARTIDA), 
  FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR),
  FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDOS(ID_PARTIDA)
);


