CREATE DATABASE DESAFIO_GRUPO6;

USE DESAFIO_GRUPO6;




CREATE TABLE TIENDA (
  ID_ARTICULOS INT PRIMARY KEY NOT NULL UNIQUE,
  NOMBRE VARCHAR(20) NULL DEFAULT NULL,
  PRECIO INT NULL DEFAULT NULL,
  ID_TIENDA INT NOT NULL UNIQUE
);


CREATE TABLE USUARIO (
  ID_USUARIO INT PRIMARY KEY NOT NULL UNIQUE,
  NOMBRE_USUARIO VARCHAR(20) NOT NULL,
  CORREO VARCHAR(50) NOT NULL,
  CONTRASEÑA VARCHAR(45) NOT NULL
 );



CREATE TABLE JUGADOR (
  ID_JUGADOR INT PRIMARY KEY NOT NULL UNIQUE,
  PUNTOS INT NOT NULL,
  ULTIMA_CONEXION DATETIME NOT NULL,
  ID_USUARIO INT NULL,
  FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);


CREATE TABLE ADMINISTRADOR (
  ID_ADMINISTRADOR INT PRIMARY KEY NOT NULL UNIQUE,
  ID_USUARIO INT NOT NULL,
  FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE ESTADISTICAS_PPT (
  ID_JUGADOR INT PRIMARY KEY,
  PIEDRA INT DEFAULT 0,
  PAPEL INT DEFAULT 0,
  TIJERA INT DEFAULT 0,
  FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR)
);

CREATE TABLE ESTADISTICAS_PPTLS (
  ID_JUGADOR INT PRIMARY KEY,
  PIEDRA INT DEFAULT 0,
  PAPEL INT DEFAULT 0,
  TIJERA INT DEFAULT 0,
  LAGARTO INT DEFAULT 0,
  SPOCK INT DEFAULT 0,
  FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR)
);

CREATE TABLE ESTADISTICAS_3_EN_RAYA (
  ID_JUGADOR INT PRIMARY KEY,
  PARTIDAS_JUGADAS INT DEFAULT 0,
  PARTIDAS_GANADAS INT DEFAULT 0,
  PARTIDAS_PERDIDAS INT DEFAULT 0,
  EMPATES INT DEFAULT 0,
  FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR)
); 

CREATE TABLE PARTIDOS (
  ID_PARTIDA INT PRIMARY KEY NOT NULL,
  FECHA DATETIME NOT NULL,
  GANADOR INT NOT NULL,
  ID_PPTLS INT NOT NULL,
  FOREIGN KEY(GANADOR) REFERENCES JUGADOR(ID_JUGADOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE
  );


CREATE TABLE Jugador_Partidos (
  ID_JUGADOR INT NOT NULL,
  ID_PARTIDA INT NOT NULL,
  `%VICTORIAS` DECIMAL(5,2),
  PRIMARY KEY (ID_JUGADOR, ID_PARTIDA), 
  FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR),
  FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDOS(ID_PARTIDA)
);

CREATE TABLE ARTICULOS_JUGADOR (
  ID_JUGADOR INT NOT NULL,
  ID_ARTICULOS INT NOT NULL,
  FEHCACOMPRA DATETIME NOT NULL,
  PRIMARY KEY (ID_JUGADOR, ID_ARTICULOS), 
  FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR),
  FOREIGN KEY (ID_ARTICULOS) REFERENCES TIENDA(ID_ARTICULOS)
);


