package main.juego;

import inicio.de.sesion.Inicio_Sesion;
import java.awt.Color;
import static java.awt.Color.green;
import perfil.usuario.Perfil_Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class Main_Juego extends javax.swing.JFrame {

    /**
     * Creates new form Main_Juego
     */
    public Main_Juego() {

        initComponents();
        Menu_Ampliado.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Cierre_de_Sesion = new javax.swing.JDialog();
        Confirmar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Rechazar_CierreSesion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Mensaje_CierreSesion = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Boton_Menu_Desplegable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu_Ampliado = new javax.swing.JPanel();
        Boton_Tienda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Boton_Ajuste = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Boton_CerrarSesion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        PanelContenido = new javax.swing.JPanel();
        Bienvenido = new javax.swing.JLabel();
        Nombre_Usuario = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PPT = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        PPTLS = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        Rayas = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        Boton_Cierre_Main = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsX.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        Cierre_de_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        Cierre_de_Sesion.setMaximumSize(new java.awt.Dimension(900, 560));
        Cierre_de_Sesion.setMinimumSize(new java.awt.Dimension(900, 560));
        Cierre_de_Sesion.setUndecorated(true);
        Cierre_de_Sesion.setPreferredSize(new java.awt.Dimension(900, 560));
        Cierre_de_Sesion.setResizable(false);
        Cierre_de_Sesion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Confirmar.setBackground(new java.awt.Color(255, 102, 102));
        Confirmar.setForeground(new java.awt.Color(204, 204, 204));
        Confirmar.setToolTipText("");
        Confirmar.setLayout(new java.awt.CardLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Si, quiero cerrar sesión");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        Confirmar.add(jLabel11, "card2");

        Cierre_de_Sesion.getContentPane().add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 380, 110));

        Rechazar_CierreSesion.setBackground(new java.awt.Color(153, 153, 153));
        Rechazar_CierreSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rechazar_CierreSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Rechazar_CierreSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Rechazar_CierreSesionMouseExited(evt);
            }
        });
        Rechazar_CierreSesion.setLayout(new java.awt.CardLayout());

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("No, no quiero cerrar sesión");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rechazar_CierreSesion.add(jLabel12, "card2");

        Cierre_de_Sesion.getContentPane().add(Rechazar_CierreSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 280, 60));

        Mensaje_CierreSesion.setBackground(new java.awt.Color(204, 204, 204));
        Mensaje_CierreSesion.setLayout(new java.awt.CardLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("¿QUIERES CERRAR SESIÓN?");
        Mensaje_CierreSesion.add(jLabel13, "card2");

        Cierre_de_Sesion.getContentPane().add(Mensaje_CierreSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 160));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 900, 10));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 160, 900, 20));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 570));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 10, 570));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 160, 900, 20));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 10));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Menu_Desplegable.setBackground(new java.awt.Color(102, 102, 102));
        Boton_Menu_Desplegable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Menu_Desplegable.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsMenu.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        Boton_Menu_Desplegable.add(jLabel1, "card2");

        jPanel1.add(Boton_Menu_Desplegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        Menu_Ampliado.setBackground(new java.awt.Color(51, 51, 51));

        Boton_Tienda.setBackground(new java.awt.Color(51, 51, 51));
        Boton_Tienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Tienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_TiendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_TiendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_TiendaMouseExited(evt);
            }
        });
        Boton_Tienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIENDA");
        Boton_Tienda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsTienda.png"))); // NOI18N
        Boton_Tienda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Tienda.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 10));

        Boton_Ajuste.setBackground(new java.awt.Color(51, 51, 51));
        Boton_Ajuste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Ajuste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_AjusteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_AjusteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_AjusteMouseExited(evt);
            }
        });
        Boton_Ajuste.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsAjustes.png"))); // NOI18N
        Boton_Ajuste.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Ajuste.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 350, 10));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PERFIL");
        Boton_Ajuste.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 50));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Menú de Opciones");

        Boton_CerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        Boton_CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_CerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_CerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_CerrarSesionMouseExited(evt);
            }
        });
        Boton_CerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\Clase\\ImagenesProgramacion (Josep)\\DESAFIO_IMAGENES\\iconsCerrarSesion.png")); // NOI18N
        jLabel9.setToolTipText("");
        Boton_CerrarSesion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 70, 68));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        Boton_CerrarSesion.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 340, 10));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("CERRAR SESIÓN");
        Boton_CerrarSesion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 50));

        javax.swing.GroupLayout Menu_AmpliadoLayout = new javax.swing.GroupLayout(Menu_Ampliado);
        Menu_Ampliado.setLayout(Menu_AmpliadoLayout);
        Menu_AmpliadoLayout.setHorizontalGroup(
            Menu_AmpliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_Tienda, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(Boton_Ajuste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu_AmpliadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(Menu_AmpliadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Boton_CerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Menu_AmpliadoLayout.setVerticalGroup(
            Menu_AmpliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_AmpliadoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(307, 307, 307)
                .addComponent(Boton_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Boton_Ajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(Boton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1.add(Menu_Ampliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 1090));

        PanelContenido.setBackground(new java.awt.Color(255, 255, 255));
        PanelContenido.setOpaque(false);
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenido.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(0, 204, 102));
        Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido.setText("BIENVENIDO ");
        PanelContenido.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 500, 100));

        Nombre_Usuario.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        Nombre_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Usuario.setText("{nombre_usuario}");
        PanelContenido.add(Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 580, 80));

        jLabel21.setBackground(new java.awt.Color(0, 255, 102));
        jLabel21.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 255, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("¿A que vamos a jugar hoy?");
        PanelContenido.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 440, 50));

        PPT.setBackground(new java.awt.Color(153, 153, 153));
        PPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PPT.setPreferredSize(new java.awt.Dimension(250, 250));
        PPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(153, 153, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/juego/PPT.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });
        PPT.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 240));

        PanelContenido.add(PPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 250, 240));

        PPTLS.setBackground(new java.awt.Color(153, 153, 153));
        PPTLS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PPTLS.setPreferredSize(new java.awt.Dimension(250, 250));
        PPTLS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\Clase\\ImagenesProgramacion (Josep)\\DESAFIO_IMAGENES\\PPTLS.png")); // NOI18N
        jLabel25.setToolTipText("");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        PPTLS.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 250));

        PanelContenido.add(PPTLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        Rayas.setBackground(new java.awt.Color(153, 153, 153));
        Rayas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Rayas.setPreferredSize(new java.awt.Dimension(250, 250));
        Rayas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\Clase\\ImagenesProgramacion (Josep)\\DESAFIO_IMAGENES\\3Raya.png")); // NOI18N
        jLabel26.setToolTipText("");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        Rayas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 250));

        PanelContenido.add(Rayas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("3 EN RAYA");
        PanelContenido.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 860, 150, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("PIEDRA PAPEL Y TIJERA");
        PanelContenido.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 850, 390, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("PIEDRA PAPEL TIJERA LAGARTO SPOCK");
        PanelContenido.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 780, 500, -1));

        jSeparator4.setBackground(new java.awt.Color(51, 255, 0));
        jSeparator4.setForeground(new java.awt.Color(51, 204, 0));
        PanelContenido.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 880, 290, 30));

        jSeparator5.setBackground(new java.awt.Color(51, 255, 0));
        jSeparator5.setForeground(new java.awt.Color(51, 204, 0));
        PanelContenido.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 810, 480, 30));

        jSeparator6.setBackground(new java.awt.Color(51, 255, 0));
        jSeparator6.setForeground(new java.awt.Color(51, 204, 0));
        PanelContenido.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 890, 140, 30));

        jPanel1.add(PanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1560, 1090));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Sheldon.png")); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 360, 730, 730));

        Boton_Cierre_Main.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Cierre_Main.setLayout(new java.awt.CardLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsX.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        Boton_Cierre_Main.add(jLabel8, "card2");

        jPanel1.add(Boton_Cierre_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 0, 90, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1980, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        if (!Menu_Ampliado.isVisible()) {
            Boton_Menu_Desplegable.setBackground(new Color(51, 51, 51));

        }
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        if (!Menu_Ampliado.isVisible()) {
            Boton_Menu_Desplegable.setBackground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        boolean abrir = !Menu_Ampliado.isVisible();
        Menu_Ampliado.setVisible(true);

        int objetivo = abrir ? 180 : 0;

        javax.swing.Timer timer = new javax.swing.Timer(5, null);
        timer.addActionListener(e -> {
            int x = PanelContenido.getX();

            if (abrir) {
                if (x < objetivo) {
                    PanelContenido.setLocation(x + 10, 0);
                } else {
                    PanelContenido.setLocation(objetivo, 0);
                    timer.stop();
                }
            } else {
                if (x > objetivo) {
                    PanelContenido.setLocation(x - 10, 0);
                } else {
                    PanelContenido.setLocation(objetivo, 0);
                    Menu_Ampliado.setVisible(false);
                    timer.stop();
                }
            }
        });

        timer.start();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered


    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited

    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel2.setBackground(Color.red);
        Boton_Cierre_Main.setBackground(Color.red);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel2.setBackground(Color.white);
        Boton_Cierre_Main.setBackground(Color.white);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void Boton_TiendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_TiendaMouseEntered
        Boton_Tienda.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_Boton_TiendaMouseEntered

    private void Boton_TiendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_TiendaMouseExited
        Boton_Tienda.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_Boton_TiendaMouseExited

    private void Boton_AjusteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AjusteMouseClicked
        new Perfil_Usuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_AjusteMouseClicked

    private void Boton_AjusteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AjusteMouseEntered
        Boton_Ajuste.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_Boton_AjusteMouseEntered

    private void Boton_AjusteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AjusteMouseExited
        Boton_Ajuste.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_Boton_AjusteMouseExited

    private void Boton_CerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionMouseEntered
        Boton_CerrarSesion.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_Boton_CerrarSesionMouseEntered

    private void Boton_CerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionMouseExited
        Boton_CerrarSesion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_Boton_CerrarSesionMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new Inicio_Sesion().setVisible(true);
        this.dispose();
        Cierre_de_Sesion.setVisible(false);

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        Confirmar.setBackground(Color.red);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        Confirmar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_jLabel11MouseExited

    private void Boton_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionMouseClicked
        Cierre_de_Sesion.setVisible(true);
    }//GEN-LAST:event_Boton_CerrarSesionMouseClicked

    private void Rechazar_CierreSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rechazar_CierreSesionMouseClicked
        Cierre_de_Sesion.setVisible(false);
    }//GEN-LAST:event_Rechazar_CierreSesionMouseClicked

    private void Rechazar_CierreSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rechazar_CierreSesionMouseEntered
        Rechazar_CierreSesion.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_Rechazar_CierreSesionMouseEntered

    private void Rechazar_CierreSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rechazar_CierreSesionMouseExited
        Rechazar_CierreSesion.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_Rechazar_CierreSesionMouseExited

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        PPT.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        PPT.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        PPTLS.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        PPTLS.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        Rayas.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        Rayas.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel26MouseExited

    private void Boton_TiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_TiendaMouseClicked

    }//GEN-LAST:event_Boton_TiendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JPanel Boton_Ajuste;
    private javax.swing.JPanel Boton_CerrarSesion;
    private javax.swing.JPanel Boton_Cierre_Main;
    private javax.swing.JPanel Boton_Menu_Desplegable;
    private javax.swing.JPanel Boton_Tienda;
    private javax.swing.JDialog Cierre_de_Sesion;
    private javax.swing.JPanel Confirmar;
    private javax.swing.JPanel Mensaje_CierreSesion;
    private javax.swing.JPanel Menu_Ampliado;
    private javax.swing.JLabel Nombre_Usuario;
    private javax.swing.JPanel PPT;
    private javax.swing.JPanel PPTLS;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JPanel Rayas;
    private javax.swing.JPanel Rechazar_CierreSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
