package pantallas;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import pantallas.juegos.PPT;
import pantallas.juegos.PPTLS;
import pantallas.juegos.Pantalla_3EnRaya;

/**
 *
 * @author LENOVO
 */
public class Main_Juego extends javax.swing.JFrame {

    /**
     * Creates new form Main_Juego
     */
    public Main_Juego() {

        initComponents();
        Menu_Ampliado.setVisible(false);

        jPanel1.setBackground(AppTheme.getFondoActivo());
        PanelContenido.setBackground(AppTheme.getFondoActivo());

        Menu_Ampliado.setBackground(new Color(20, 20, 20));
        Sheldon.setIcon(AppTheme.getPersonajeMainActivo());
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Cierre_de_Sesion = new javax.swing.JDialog();
        Confirmar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Rechazar_CierreSesion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Mensaje_CierreSesion = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Boton_Menu_Desplegable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu_Ampliado = new javax.swing.JPanel();
        Boton_Tienda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Boton_Ajuste = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Boton_CerrarSesion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        PanelContenido = new javax.swing.JPanel();
        Bienvenido = new javax.swing.JLabel();
        duda = new javax.swing.JLabel();
        panelPPT = new javax.swing.JPanel();
        botonJugarPPT = new javax.swing.JPanel();
        ppt = new javax.swing.JLabel();
        panelPPTLS = new javax.swing.JPanel();
        botonJugarPPTLS = new javax.swing.JPanel();
        pptls = new javax.swing.JLabel();
        panelRAYA = new javax.swing.JPanel();
        botonJugarRAYA = new javax.swing.JPanel();
        ppt2 = new javax.swing.JLabel();
        mensajito = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        mando = new javax.swing.JLabel();
        Boton_Cierre_Main = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sheldon = new javax.swing.JLabel();
        saturno = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsX.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        Cierre_de_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        Cierre_de_Sesion.setMinimumSize(new java.awt.Dimension(900, 560));
        Cierre_de_Sesion.setUndecorated(true);
        Cierre_de_Sesion.setResizable(false);
        Cierre_de_Sesion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Confirmar.setBackground(new java.awt.Color(255, 102, 102));
        Confirmar.setForeground(new java.awt.Color(204, 204, 204));
        Confirmar.setToolTipText("");
        Confirmar.setLayout(new java.awt.CardLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Si, quiero cerrar sesión");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        Confirmar.add(jLabel11, "card2");

        Cierre_de_Sesion.getContentPane().add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 380, 110));

        Rechazar_CierreSesion.setBackground(new java.awt.Color(153, 153, 153));
        Rechazar_CierreSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rechazar_CierreSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Rechazar_CierreSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Rechazar_CierreSesionMouseExited(evt);
            }
        });
        Rechazar_CierreSesion.setLayout(new java.awt.CardLayout());

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("No, no quiero cerrar sesión");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Rechazar_CierreSesion.add(jLabel12, "card2");

        Cierre_de_Sesion.getContentPane().add(Rechazar_CierreSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 280, 60));

        Mensaje_CierreSesion.setBackground(new java.awt.Color(204, 204, 204));
        Mensaje_CierreSesion.setLayout(new java.awt.CardLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("¿QUIERES CERRAR SESIÓN?");
        Mensaje_CierreSesion.add(jLabel13, "card2");

        Cierre_de_Sesion.getContentPane().add(Mensaje_CierreSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 160));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 900, 10));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 160, 900, 20));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 570));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 10, 570));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 160, 900, 20));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setOpaque(true);
        Cierre_de_Sesion.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 10));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Menu_Desplegable.setBackground(new java.awt.Color(18, 18, 18));
        Boton_Menu_Desplegable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_Menu_Desplegable.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(18, 18, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsMenu.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        Boton_Menu_Desplegable.add(jLabel1, "card2");

        jPanel1.add(Boton_Menu_Desplegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        Menu_Ampliado.setBackground(new java.awt.Color(22, 22, 22));
        Menu_Ampliado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Tienda.setBackground(new java.awt.Color(22, 22, 22));
        Boton_Tienda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_Tienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_TiendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_TiendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_TiendaMouseExited(evt);
            }
        });
        Boton_Tienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIENDA");
        Boton_Tienda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsTienda.png"))); // NOI18N
        Boton_Tienda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Tienda.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 10));

        Menu_Ampliado.add(Boton_Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 363, 360, 59));

        Boton_Ajuste.setBackground(new java.awt.Color(22, 22, 22));
        Boton_Ajuste.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_Ajuste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_AjusteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_AjusteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_AjusteMouseExited(evt);
            }
        });
        Boton_Ajuste.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsAjustes.png"))); // NOI18N
        Boton_Ajuste.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Ajuste.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 350, 10));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PERFIL");
        Boton_Ajuste.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 50));

        Menu_Ampliado.add(Boton_Ajuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 469, 360, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Menú de Opciones");
        Menu_Ampliado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 32, 210, -1));

        Boton_CerrarSesion.setBackground(new java.awt.Color(22, 22, 22));
        Boton_CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_CerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_CerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_CerrarSesionMouseExited(evt);
            }
        });
        Boton_CerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsCerrarSesion.png"))); // NOI18N
        jLabel9.setToolTipText("");
        Boton_CerrarSesion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 70, 68));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        Boton_CerrarSesion.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 340, 10));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("CERRAR SESIÓN");
        Boton_CerrarSesion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 50));

        Menu_Ampliado.add(Boton_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 980, 360, -1));

        jPanel1.add(Menu_Ampliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 1090));

        PanelContenido.setBackground(new java.awt.Color(18, 18, 18));
        PanelContenido.setOpaque(false);
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenido.setFont(new java.awt.Font("Sans Serif Collection", 1, 54)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(0, 255, 170));
        Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido.setText("BIENVENIDO {nombre_usuario} !");
        PanelContenido.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 1100, 100));

        duda.setBackground(new java.awt.Color(0, 255, 102));
        duda.setFont(new java.awt.Font("Sans Serif Collection", 1, 36)); // NOI18N
        duda.setForeground(new java.awt.Color(51, 255, 204));
        duda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        duda.setText("¿A que vamos a jugar hoy?");
        PanelContenido.add(duda, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 500, 50));

        panelPPT.setOpaque(false);
        panelPPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPPTMouseEntered(evt);
            }
        });
        panelPPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonJugarPPT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonJugarPPT.setOpaque(false);
        botonJugarPPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonJugarPPTMouseClicked(evt);
            }
        });
        panelPPT.add(botonJugarPPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 250, 70));

        ppt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PPT.png"))); // NOI18N
        ppt.setText("jLabel22");
        panelPPT.add(ppt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, -1));

        PanelContenido.add(panelPPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 430, 670));

        panelPPTLS.setOpaque(false);
        panelPPTLS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonJugarPPTLS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonJugarPPTLS.setOpaque(false);
        botonJugarPPTLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonJugarPPTLSMouseClicked(evt);
            }
        });
        panelPPTLS.add(botonJugarPPTLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 240, 70));

        pptls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pptls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PPTLS.png"))); // NOI18N
        panelPPTLS.add(pptls, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, -1));

        PanelContenido.add(panelPPTLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 440, 670));

        panelRAYA.setOpaque(false);
        panelRAYA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonJugarRAYA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonJugarRAYA.setOpaque(false);
        botonJugarRAYA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonJugarRAYAMouseClicked(evt);
            }
        });
        panelRAYA.add(botonJugarRAYA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 240, 70));

        ppt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RAYA.png"))); // NOI18N
        ppt2.setText("jLabel22");
        panelRAYA.add(ppt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, -1));

        PanelContenido.add(panelRAYA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 190, 430, 670));

        mensajito.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        mensajito.setForeground(new java.awt.Color(153, 153, 153));
        mensajito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajito.setText("Diviértete y desafía tu mente");
        PanelContenido.add(mensajito, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 990, 300, 70));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        PanelContenido.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1020, 170, 20));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));
        PanelContenido.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 1020, 170, 20));

        mando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsVidejuego.png"))); // NOI18N
        PanelContenido.add(mando, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 930, 80, 70));

        jPanel1.add(PanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1700, 1090));

        Boton_Cierre_Main.setBackground(new java.awt.Color(18, 18, 18));
        Boton_Cierre_Main.setLayout(new java.awt.CardLayout());

        jLabel8.setBackground(new java.awt.Color(18, 18, 18));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsX_Blanco.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        Boton_Cierre_Main.add(jLabel8, "card2");

        jPanel1.add(Boton_Cierre_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 0, 90, 90));

        Sheldon.setBackground(new java.awt.Color(204, 204, 204));
        Sheldon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sheldon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sheldon.png"))); // NOI18N
        jPanel1.add(Sheldon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 1000, 1070));

        saturno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saturno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/saturno.png"))); // NOI18N
        jPanel1.add(saturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1980, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        if (!Menu_Ampliado.isVisible()) {
            Boton_Menu_Desplegable.setBackground(new Color(27,27,27));

        }
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        if (!Menu_Ampliado.isVisible()) {
            Boton_Menu_Desplegable.setBackground(new Color(18,18,18));
        }
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        boolean abrir = !Menu_Ampliado.isVisible();
        Menu_Ampliado.setVisible(true);

        int objetivo = abrir ? 180 : 0;

        javax.swing.Timer timer = new javax.swing.Timer(5, null);
        timer.addActionListener(e -> {
            int x = PanelContenido.getX();

            if (abrir) {
                if (x < objetivo) {
                    PanelContenido.setLocation(x + 10, 0);
                } else {
                    PanelContenido.setLocation(objetivo, 0);
                    timer.stop();
                }
            } else {
                if (x > objetivo) {
                    PanelContenido.setLocation(x - 10, 0);
                } else {
                    PanelContenido.setLocation(objetivo, 0);
                    Menu_Ampliado.setVisible(false);
                    timer.stop();
                }
            }
        });

        timer.start();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered


    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited

    }//GEN-LAST:event_jLabel7MouseExited

    private void Boton_TiendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_TiendaMouseEntered
        Boton_Tienda.setBackground(new Color(45, 45, 45));
    }//GEN-LAST:event_Boton_TiendaMouseEntered

    private void Boton_TiendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_TiendaMouseExited
        Boton_Tienda.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_Boton_TiendaMouseExited

    private void Boton_AjusteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AjusteMouseClicked
        new Perfil_Usuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_AjusteMouseClicked

    private void Boton_AjusteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AjusteMouseEntered
        Boton_Ajuste.setBackground(new Color(45, 45, 45));
    }//GEN-LAST:event_Boton_AjusteMouseEntered

    private void Boton_AjusteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AjusteMouseExited
        Boton_Ajuste.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_Boton_AjusteMouseExited

    private void Boton_CerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionMouseEntered
        Boton_CerrarSesion.setBackground(new Color(45, 45, 45));
    }//GEN-LAST:event_Boton_CerrarSesionMouseEntered

    private void Boton_CerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionMouseExited
        Boton_CerrarSesion.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_Boton_CerrarSesionMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new Inicio_Sesion().setVisible(true);
        this.dispose();
        Cierre_de_Sesion.setVisible(false);

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        Confirmar.setBackground(Color.red);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        Confirmar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_jLabel11MouseExited

    private void Boton_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionMouseClicked
        Cierre_de_Sesion.setVisible(true);
    }//GEN-LAST:event_Boton_CerrarSesionMouseClicked

    private void Rechazar_CierreSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rechazar_CierreSesionMouseClicked
        Cierre_de_Sesion.setVisible(false);
    }//GEN-LAST:event_Rechazar_CierreSesionMouseClicked

    private void Rechazar_CierreSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rechazar_CierreSesionMouseEntered
        Rechazar_CierreSesion.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_Rechazar_CierreSesionMouseEntered

    private void Rechazar_CierreSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rechazar_CierreSesionMouseExited
        Rechazar_CierreSesion.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_Rechazar_CierreSesionMouseExited

    private void Boton_TiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_TiendaMouseClicked
        new Tienda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_TiendaMouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel2.setBackground(new Color(18, 18, 18));
        Boton_Cierre_Main.setBackground(new Color(18, 18, 18));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel2.setBackground(Color.red);
        Boton_Cierre_Main.setBackground(Color.red);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void panelPPTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPPTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPPTMouseEntered

    private void botonJugarPPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarPPTMouseClicked
        new PPT().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonJugarPPTMouseClicked

    private void botonJugarPPTLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarPPTLSMouseClicked
        new PPTLS().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botonJugarPPTLSMouseClicked

    private void botonJugarRAYAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarRAYAMouseClicked
        new Pantalla_3EnRaya().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botonJugarRAYAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JPanel Boton_Ajuste;
    private javax.swing.JPanel Boton_CerrarSesion;
    private javax.swing.JPanel Boton_Cierre_Main;
    private javax.swing.JPanel Boton_Menu_Desplegable;
    private javax.swing.JPanel Boton_Tienda;
    private javax.swing.JDialog Cierre_de_Sesion;
    private javax.swing.JPanel Confirmar;
    private javax.swing.JPanel Mensaje_CierreSesion;
    private javax.swing.JPanel Menu_Ampliado;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JPanel Rechazar_CierreSesion;
    private javax.swing.JLabel Sheldon;
    private javax.swing.JPanel botonJugarPPT;
    private javax.swing.JPanel botonJugarPPTLS;
    private javax.swing.JPanel botonJugarRAYA;
    private javax.swing.JLabel duda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel mando;
    private javax.swing.JLabel mensajito;
    private javax.swing.JPanel panelPPT;
    private javax.swing.JPanel panelPPTLS;
    private javax.swing.JPanel panelRAYA;
    private javax.swing.JLabel ppt;
    private javax.swing.JLabel ppt2;
    private javax.swing.JLabel pptls;
    private javax.swing.JLabel saturno;
    // End of variables declaration//GEN-END:variables
}
