package pantallas;

import CRUD_bbdd.bbdd_registroUsuario;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.red;
import static java.awt.Color.white;
import static java.awt.Color.yellow;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Registro extends javax.swing.JFrame {

    private final char EchoChar;

    ImageIcon NoVer = new ImageIcon("src\\imagenes\\iconsNoVer.png");
    ImageIcon Ver = new ImageIcon("src\\imagenes\\iconsVer.png");

    int xMouse, yMouse;

    public Registro() {
        initComponents();
        EchoChar = contraseña.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANELGRANDE_REGISTRO = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PANEL_INICIO_SESION = new javax.swing.JPanel();
        contraseña = new javax.swing.JPasswordField();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        PanelAcceso = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BOTON_CERRAR_Registro = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        PanelVolverIncio = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Visibilidad = new javax.swing.JLabel();
        Panel_Arrastre = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANELGRANDE_REGISTRO.setBackground(new java.awt.Color(255, 255, 255));
        PANELGRANDE_REGISTRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BannerDesafíoRegistro.png"))); // NOI18N
        jLabel1.setOpaque(true);
        PANELGRANDE_REGISTRO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 470, 600));

        PANEL_INICIO_SESION.setBackground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(204, 204, 204));
        contraseña.setText("********");
        contraseña.setBorder(null);
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseñaMouseClicked(evt);
            }
        });
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        PANEL_INICIO_SESION.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 40));

        nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("Ingresar Nombre Aquí");
        nombre.setBorder(null);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        PANEL_INICIO_SESION.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, 40));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REGISTRATE");
        PANEL_INICIO_SESION.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 140));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsUsuario.png"))); // NOI18N
        PANEL_INICIO_SESION.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 255, 204));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 340, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Contraseña");
        PANEL_INICIO_SESION.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsSeguridad.png"))); // NOI18N
        PANEL_INICIO_SESION.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 60, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 255, 204));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 340, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 600));

        PanelAcceso.setBackground(new java.awt.Color(0, 204, 204));
        PanelAcceso.setLayout(new java.awt.CardLayout());

        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EMPEZAR A JUGAR");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        PanelAcceso.add(jLabel8, "card2");

        PANEL_INICIO_SESION.add(PanelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 230, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 10, 600));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setText("Nombre");
        PANEL_INICIO_SESION.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        BOTON_CERRAR_Registro.setBackground(new java.awt.Color(255, 255, 255));
        BOTON_CERRAR_Registro.setLayout(new java.awt.CardLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsX.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        BOTON_CERRAR_Registro.add(jLabel16, "card2");

        PANEL_INICIO_SESION.add(BOTON_CERRAR_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        correo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(204, 204, 204));
        correo.setText("Ingresar Aquí");
        correo.setBorder(null);
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoMouseClicked(evt);
            }
        });
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        PANEL_INICIO_SESION.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 230, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsMail.png"))); // NOI18N
        PANEL_INICIO_SESION.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 60, 50));

        jSeparator4.setBackground(new java.awt.Color(0, 255, 204));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 340, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setText("Correo Electrónico");
        PANEL_INICIO_SESION.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        PanelVolverIncio.setBackground(new java.awt.Color(102, 204, 0));
        PanelVolverIncio.setLayout(new java.awt.CardLayout());

        jLabel13.setBackground(new java.awt.Color(153, 204, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Volver a incio de sesion");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        PanelVolverIncio.add(jLabel13, "card2");

        PANEL_INICIO_SESION.add(PanelVolverIncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 190, 30));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 570, 10));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 10));

        Visibilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Visibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsVer.png"))); // NOI18N
        Visibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisibilidadMouseClicked(evt);
            }
        });
        PANEL_INICIO_SESION.add(Visibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, 40));

        PANELGRANDE_REGISTRO.add(PANEL_INICIO_SESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 600));

        Panel_Arrastre.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Arrastre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_ArrastreMouseDragged(evt);
            }
        });
        Panel_Arrastre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_ArrastreMousePressed(evt);
            }
        });
        PANELGRANDE_REGISTRO.add(Panel_Arrastre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 980, 30));

        getContentPane().add(PANELGRANDE_REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        PanelAcceso.setBackground(yellow);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        PanelAcceso.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        BOTON_CERRAR_Registro.setBackground(red);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        BOTON_CERRAR_Registro.setBackground(white);
    }//GEN-LAST:event_jLabel16MouseExited

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed

    }//GEN-LAST:event_correoActionPerformed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        PanelVolverIncio.setBackground(new Color(153, 204, 0));
        jLabel13.setForeground(white);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        PanelVolverIncio.setBackground(new Color(153, 153, 0));
        jLabel13.setForeground(black);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        new Inicio_Sesion().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel13MouseClicked

    private void Panel_ArrastreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ArrastreMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Panel_ArrastreMouseDragged

    private void Panel_ArrastreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ArrastreMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Panel_ArrastreMousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        registrarUsuario();
    }//GEN-LAST:event_jLabel8MouseClicked


    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        nombre.setText("");
    }//GEN-LAST:event_nombreMouseClicked

    private void correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMouseClicked
        correo.setText("");
    }//GEN-LAST:event_correoMouseClicked

    private void VisibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisibilidadMouseClicked
        if (contraseña.getEchoChar() == EchoChar) {
            Visibilidad.setIcon(NoVer);
            contraseña.setEchoChar((char) 0);
        } else {
            Visibilidad.setIcon(Ver);
            contraseña.setEchoChar(EchoChar);
        }
    }//GEN-LAST:event_VisibilidadMouseClicked

    private void contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaMouseClicked
        contraseña.setText("");
    }//GEN-LAST:event_contraseñaMouseClicked

    private void registrarUsuario() {
        String nombreUsuario = nombre.getText().trim();
        String correoUsuario = correo.getText().trim();
        String contrasenaUsuario = new String(contraseña.getPassword()).trim();

        if (!datosRegistroValidos(nombreUsuario, correoUsuario, contrasenaUsuario)) {
            return;
        }

        if (bbdd_registroUsuario.existeUsuarioOCorreo(nombreUsuario, correoUsuario)) {
            JOptionPane.showMessageDialog(this, "Ese nombre o correo ya esta registrado.", "Registro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean registrado = bbdd_registroUsuario.registrarUsuario(nombreUsuario, correoUsuario, contrasenaUsuario);

        if (registrado) {
            AppTheme.setNombreUsuarioActivo(nombreUsuario);
            new Main_Juego().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario. Revisa la conexion con la base de datos.", "Registro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean datosRegistroValidos(String nombreUsuario, String correoUsuario, String contrasenaUsuario) {
        if (nombreUsuario.isEmpty() || nombreUsuario.equals("Ingresar Nombre Aquí")) {
            JOptionPane.showMessageDialog(this, "Introduce un nombre de usuario.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (correoUsuario.isEmpty() || correoUsuario.equals("Ingresar Aquí")) {
            JOptionPane.showMessageDialog(this, "Introduce un correo electronico.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (!correoUsuario.contains("@") || !correoUsuario.contains(".")) {
            JOptionPane.showMessageDialog(this, "Introduce un correo electronico valido.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (contrasenaUsuario.isEmpty() || contrasenaUsuario.equals("********")) {
            JOptionPane.showMessageDialog(this, "Introduce una contraseña.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (nombreUsuario.length() > 20) {
            JOptionPane.showMessageDialog(this, "El nombre no puede superar 20 caracteres.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (correoUsuario.length() > 50) {
            JOptionPane.showMessageDialog(this, "El correo no puede superar 50 caracteres.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (contrasenaUsuario.length() > 45) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede superar 45 caracteres.", "Registro", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BOTON_CERRAR_Registro;
    private javax.swing.JPanel PANELGRANDE_REGISTRO;
    private javax.swing.JPanel PANEL_INICIO_SESION;
    private javax.swing.JPanel PanelAcceso;
    private javax.swing.JPanel PanelVolverIncio;
    private javax.swing.JPanel Panel_Arrastre;
    private javax.swing.JLabel Visibilidad;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
