/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicio.de.sesion;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.white;
import main.juego.Main_Juego;
import registro.de.sesion.Registro;

public class Inicio_Sesion extends javax.swing.JFrame {

    int xMouse, yMouse;

    public Inicio_Sesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel16 = new javax.swing.JLabel();
        PANELGRANDE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PANEL_INICIO_SESION = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        PanelAcceso = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PANEL_MENSAJE_REGISTRO = new javax.swing.JPanel();
        BOTON_REGISTRO = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BOTON_CERRAR = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Arrastre = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jEditorPane1);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        PANELGRANDE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BannerDesafío.png"))); // NOI18N
        jLabel1.setOpaque(true);
        PANELGRANDE.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 600));

        PANEL_INICIO_SESION.setBackground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("********");
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        PANEL_INICIO_SESION.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 230, 40));

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Ingresar Aquí");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PANEL_INICIO_SESION.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, 40));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIAR SESIÓN");
        PANEL_INICIO_SESION.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 140));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsUsuario.png"))); // NOI18N
        PANEL_INICIO_SESION.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 255, 204));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 340, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Contraseña");
        PANEL_INICIO_SESION.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsSeguridad.png"))); // NOI18N
        PANEL_INICIO_SESION.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 60, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 255, 204));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PANEL_INICIO_SESION.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 340, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 600));

        PanelAcceso.setBackground(new java.awt.Color(0, 204, 204));
        PanelAcceso.setLayout(new java.awt.CardLayout());

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ENTRAR");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        PanelAcceso.add(jLabel7, "card2");

        PANEL_INICIO_SESION.add(PanelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 150, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 10, 600));

        PANEL_MENSAJE_REGISTRO.setBackground(new java.awt.Color(153, 153, 153));
        PANEL_MENSAJE_REGISTRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BOTON_REGISTRO.setBackground(new java.awt.Color(255, 255, 255));
        BOTON_REGISTRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTON_REGISTROMouseClicked(evt);
            }
        });
        BOTON_REGISTRO.setLayout(new java.awt.CardLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("¡REGISTRATE!");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        BOTON_REGISTRO.add(jLabel11, "card2");

        PANEL_MENSAJE_REGISTRO.add(BOTON_REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 240, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("¿No tienes cuenta y quieres empezar a jugar?");
        PANEL_MENSAJE_REGISTRO.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 400, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PINCHA AQUÍ PARA CREAR UNA CUENTA");
        PANEL_MENSAJE_REGISTRO.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 400, 20));

        PANEL_INICIO_SESION.add(PANEL_MENSAJE_REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 570, 140));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setText("Nombre o Correo Electrónico");
        PANEL_INICIO_SESION.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setOpaque(true);
        PANEL_INICIO_SESION.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 570, 10));

        BOTON_CERRAR.setBackground(new java.awt.Color(255, 255, 255));
        BOTON_CERRAR.setLayout(new java.awt.CardLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsX.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        BOTON_CERRAR.add(jLabel2, "card2");

        PANEL_INICIO_SESION.add(BOTON_CERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, 40));

        Panel_Arrastre.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Arrastre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_ArrastreMouseDragged(evt);
            }
        });
        Panel_Arrastre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_ArrastreMousePressed(evt);
            }
        });
        PANEL_INICIO_SESION.add(Panel_Arrastre, new org.netbeans.lib.awtextra.AbsoluteConstraints(-460, 0, 980, 30));

        PANELGRANDE.add(PANEL_INICIO_SESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 570, -1));

        getContentPane().add(PANELGRANDE, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(Color.red);
        BOTON_CERRAR.setBackground(Color.red);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBackground(Color.white);
        BOTON_CERRAR.setBackground(Color.white);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(white);
        PanelAcceso.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        PanelAcceso.setBackground(new Color(0, 204, 204));
        jLabel7.setForeground(black);

    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        BOTON_REGISTRO.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        BOTON_REGISTRO.setBackground(Color.white);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new Registro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void Panel_ArrastreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ArrastreMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Panel_ArrastreMousePressed

    private void Panel_ArrastreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ArrastreMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Panel_ArrastreMouseDragged

    private void BOTON_REGISTROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTON_REGISTROMouseClicked
    new Registro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BOTON_REGISTROMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new Main_Juego().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BOTON_CERRAR;
    private javax.swing.JPanel BOTON_REGISTRO;
    private javax.swing.JPanel PANELGRANDE;
    private javax.swing.JPanel PANEL_INICIO_SESION;
    private javax.swing.JPanel PANEL_MENSAJE_REGISTRO;
    private javax.swing.JPanel PanelAcceso;
    private javax.swing.JPanel Panel_Arrastre;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
