name: Java Hybrid Build (Maven + Ant) & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Configurar Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: 'maven'

    # Compilar logica (Maven):
    - name: Compilar LogicaJuegos
      run: |
        cd Materializacion/LogicaJuegos
        mvn clean package
        ls -al target

    # Preparar dependencias:
    - name: Obtener otras dependencias
      run: |
        cd Materializacion/ApartadoVisual
        mkdir -p lib
        
        # nos bajamos AbsoluteLayout y el jdbc desde maven.org:
        wget -O lib/mysql-connector-j-9.7.0.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.7.0/mysql-connector-j-9.7.0.jar
        wget -O lib/AbsoluteLayout.jar https://repo1.maven.org/maven2/org/netbeans/external/AbsoluteLayout/RELEASE140/AbsoluteLayout-RELEASE140.jar

    # Compilar y empaquetar (Ant):
    - name: Compilar ApartadoVisual y empaquetar
      run: |
        cd Materializacion/ApartadoVisual
        ant -Dplatforms.JDK_22.home=$JAVA_HOME \
            -Dlibs.absolutelayout.classpath=lib/AbsoluteLayout.jar \
            -Dlibs.mysql-connector-j-9.7.0.classpath=lib/mysql-connector-j-9.7.0.jar \
            clean jar
        ls -al dist

    # Comprimir
    - name: Comprimir carpeta dist a ZIP
      run: |
        cd Materializacion/ApartadoVisual
        zip -r ../../DESAFIO-EQUIPO-6.zip dist/*

    # Crear Release
    - name: Crear GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: DESAFIO-EQUIPO-6.zip
        name: Release ${{ github.ref_name }}
        draft: true
        prerelease: ${{ startsWith(github.ref_name, 'v0') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
